namespace FYA.PInvoke
{
    public enum DiFunction
    {
        SelectDevice = 1,
        InstallDevice,
        AssignResources,
        Properties,
        Remove,
        FirstTimeSetup,
        FoundDevice,
        SelectClassDrivers,
        ValidateClassDrivers,
        InstallClassDrivers,
        CalcDiskSpace,
        DestroyPrivateData,
        ValidateDriver,
        Detect = 15,
        InstallWizard,
        DestroyWizardData,
        PropertyChange,
        EnableClass,
        DetectVerify,
        InstallDeviceFiles,
        UnRemove,
        SelectBestCompatDrv,
        AllowInstal,
        RegisterDevice,
        NewDeviceWizardPreSelect,
        NewDeviceWizardSelect,
        NewDeviceWizardPreAnalyze,
        NewDeviceWizardPostAnalyze,
        NewDeviceWizardFinishInstall,
        Unused1,
        InstallInterfaces,
        DetectCancel,
        RegisterCoInstallers,
        AddPropertyPageAdvanced,
        AddPropertyPageBasic,
        Reserved1,
        Troubleshooter,
        PowerMessageWake,
        AddRemotePropertyPageAdvanced,
        UpdateDriverUI,
        Reserved2 = 48
    }
}
